# Generated by Django 4.1.5 on 2023-05-06 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100, verbose_name='full name')),
                ('emailid', models.EmailField(max_length=100, verbose_name='emailid')),
                ('contact', models.IntegerField(max_length=10, verbose_name='contanct number')),
                ('address', models.CharField(max_length=100, verbose_name='address')),
                ('username', models.CharField(max_length=20, verbose_name='username')),
                ('password', models.CharField(max_length=20, verbose_name='password')),
            ],
        ),
    ]
